### ISSUE TITLE
Set Community Standards

### ISSUE THREAD

**Issue by TheDan64** [TheDan64/inkwell#11]
- [x] Contributing.md
- [x] Code of Conduct.md
- [x] PR Template (ie document & test new methods)
- [x] Issue Template

**Comment by 6A** [comment]
Should we track some ideas here? For instance, contributions now require each added / modified function to be properly documented (maybe tested as well?)

**Comment by TheDan64** [comment]
I've added a PR template. Feel free to provide feedback here on format or content next time you submit a PR.

**Comment by 6A** [comment]
It's nice, but I find it a little overwhelming. It looks like it was made for pretty huge commits, and a simple fix or doc change for example requires a pretty long form to be submitted.

**Comment by TheDan64** [comment]
True. What parts do you think should be reduced or removed?

**Comment by 6A** [comment]
1. The checklist could instead be a single checkbox that reads "I have read the \[Contributing guide\]\(./CONTRIBUTING.md\)" or, since GitHub automatically shows a message referring to it, the checklist could be completely removed.
2. "Motivation and Context" doesn't seem extremely relevant. "Why is this change required? What problem does it solve?" are self-explanatory (either through the description, or thanks to the related issue).
3. Some parts should be explicitly optional. For example, an additional "Breaking changes" part would be useful if breaking changes are introduced, and would render the "Types of Change" part useless (since whether it's a bug fix or feature change is answered in the related issue).

**Comment by TheDan64** [comment]
Those are all great points. Will take them into consideration. Thanks!

**Comment by TheDan64** [comment]
Addressed COC 4ef6045c12e08b62338ebd8db07e108514e140df and issue templates 7bdd8702804075eb2625c04daf388db8e11a6981
