### ISSUE TITLE
New bindings for LLVM 9.*

### ISSUE THREAD

**Issue by vertexclique** [TheDan64/inkwell#143]
Hi 👋 
It would be nice to have LLVM 9 bindings exposed in a separate branch.
That will help me a lot for a project that I want to publish soon.

**Comment by TheDan64** [comment]
Now that there exists a v90 of llvm-sys, this should be possible now. I believe @bitwalker started working on this?

**Comment by bitwalker** [comment]
I actually have a branch [here](https://github.com/lumen/inkwell/tree/llvm-9.0) which is essentially finished, though I have been working primarily in C++ with LLVM as of late, so I'm a few commits behind master. The only real thing required to finalize the branch is to rebase the changes on master and switch to using the v90 branch of llvm-sys now that it exists (I had my own branch of llvm-sys, since it was taking so long).

In any case, @TheDan64 if you can take a look, let me know if you think the changes there are looking good relative to how you want things done, and I'll clean up the branch and open a PR!

**Comment by TheDan64** [comment]
@bitwalker Would you mind putting up a PR? It'll be harder for me to forget about with an actual PR, plus I can add comments on things that need to change, if any.

**Comment by TheDan64** [comment]
LLVM 9 and 10 branches are now available
