### ISSUE TITLE
Segfaults when builder is called without setting its position first

### ISSUE THREAD

**Issue by jdupak** [TheDan64/inkwell#425]
**Describe the Bug**
Program compiles successfully but segfaults, if builder position is not set to some BB.

**To Reproduce**

```rust
        let main = module.add_function("main", ctx.i64_type().fn_type(&[], false), None);
        let entry = ctx.append_basic_block(main, "entry");
        // builder.position_at_end(entry); without this is segfaults
        let exit_code = builder.build_alloca(ctx.i64_type(), "exit_code");
        let exit_bb = ctx.append_basic_block(main, "exit");
```

**Expected Behavior**
This should at least produce a "controled" runtime error.

**LLVM Version (please complete the following information):**
 - LLVM Version: 11, 14
 - Inkwell Branch Used: crates.io release 0.2.0

**Desktop (please complete the following information):**
 - OS: Manjaro

**Comment by TheDan64** [comment]
I wanna say this is a known issue but I can't find a ticket for it lol.

Not sure the LLVM api has a safe way for us to verify if a position has been set

**Comment by marcospb19** [comment]
I was about to open an issue, but found this one.

```rust
use inkwell::context::Context;

fn main() {
    let context = Context::create();
    let builder = context.create_builder();

    // [1] 70215 segmentation fault (core dumped)
    builder.build_alloca(context.i64_type(), &"n");
}
```

```toml
inkwell = { version = "0.2.0", features = ["llvm15-0"] }
```

**Comment by EricLBuehler** [comment]
> if builder position is not set to some BB.

Perhaps Inkwell can store a state of BB, so that it has a runtime error? Or better yet, a type-state of some sort?

**Comment by TheDan64** [comment]
Yeah, I've thought about using type state for this before but we'd have to figure out which methods are valid for each state and there are a lot of builder methods

**Comment by EricLBuehler** [comment]
I agree, it would be complicated to implement type state.

To implement type state based safety, perhaps a builer pattern can be implemented for the `Builder` struct. With this idea, the only way a "buildable"  `Builder` can be created is by calling one of the `position_*` methods on a "non-buildable" `Builder`? This would return a "buildable"  `Builder` and would essentially be a `build` method for the builder pattern.

However, as someone who uses Inkwell in my own projects, I think this would be cumbersome from an API useability point of view. For example, a `Builder<State=NotSet>` and then an `Option<Builder<State=Set>>` would need to be kept in order to use type state safety. In addition, backwards compatibility would be an issue. However, the major improvement this would bring is that no segfaults are caused by a simple mistake.

For those reasons, I am think runtime assertions to ensure safety by adding state to the `Builder` struct would be better.
