### ISSUE TITLE
Extern functions are not detected by Kaleidoscope JIT

### ISSUE THREAD

**Issue by OlegTheCat** [TheDan64/inkwell#74]
**Describe the Bug**
[As stated in the comment](https://github.com/TheDan64/inkwell/blob/b541566a0ac18a0f52bef54596d00c740c8b0597/examples/kaleidoscope/main.rs#L1186-L1192) extern functions defined in Rust code are not detected by Kaleidoscope JIT.

**To Reproduce**
1. Run Kaleidoscope REPL.
2. Type `extern printd(x)`
3. Type `printd(10)`
4. Function returns `NaN`

**Expected Behavior**
`printd` function should have returned passed value and printed it.

**LLVM Version (please complete the following information):**
 - LLVM Version: 7.0.1
 - Inkwell Branch Used: llvm7-0

**Desktop (please complete the following information):**
 - OS: OS X

**Additional Context**
After a bit of investigation, it seems that there are a couple of problems here:

1. `rustc` will mangle the names of those function unless `#[no_mangle]` attribute is applied.
2. Unless those functions are used in the Rust code, the compiler will remove them. To avoid this they should be called somewhere or put into a static array with `#[used]` attribute like [here](https://github.com/rust-lang/rust/pull/39987).
3. Currently, [body that returns `NaN` is set for `extern` functions](https://github.com/TheDan64/inkwell/blob/b541566a0ac18a0f52bef54596d00c740c8b0597/examples/kaleidoscope/main.rs#L519-L523). This causes that functions that are defined in Rust are being overridden by those that return `NaN` (strangely, but functions like `sin` and `cos` are not being overridden). It seems that if we got `extern` definition, we should not attach any body to it.

I kinda [fixed](https://github.com/OlegTheCat/inkwell/commit/5c1ce9e0979354f34d0ea7df22c9bf51cf888110) these issues in my fork, but it will segfault if `extern` function, that is not actually defined, is called. I'm not sure what is desired behavior here. Let me know what do you think about this.

**Comment by TheDan64** [comment]
@71 As the original author of this code, any thoughts on this?

**Comment by 71** [comment]
I remember struggling to make extern functions work, before giving up after trying several different things. I do remember trying to add `#[no_mangle]`, but am not sure I took the necessary steps to ensure the functions were not removed by the Rust compiler. I'm glad you managed to make it work!

I feel like the segfault behavior is more of an Inkwell problem than a Kaleidoscope problem, but even then finding a suitable solution is hard. Maybe documenting some function, type or module suitably to explain the different steps that must be taken to make extern functions work will be a good first step, since wrapping user code to avoid segfaults in practically impossible.

Regarding the fix itself, I think the choice to make `body` an `Option` is the right one.

**Comment by TheDan64** [comment]
Shouldn't Kaleidoscope be using External Linkage?

https://github.com/TheDan64/inkwell/blob/4630dd2a5b214fc879dfa43e56eedbb9de875432/src/module.rs#L82-L84

I don't believe it does

**Comment by TheDan64** [comment]
@OlegTheCat Any luck with your fork? We'd be happy to accept a PR if you can get it fully working

**Comment by OlegTheCat** [comment]
So, the C++ version seems not to segfault, but the issue is that it uses different API for JITting (which is old and deprecated right not, btw). I'm currently struggling to map it to the new API through `inkwell <-> llvm-sys <-> llvm-c <-> llvm-c++` chain. It seems I'll need more time to investigate this.

**Comment by TheDan64** [comment]
Thanks for taking a look at this! Did you try the C version of kaleidoscope?

**Comment by OlegTheCat** [comment]
I'm pasting my previous comment here. Sorry for the confusion.

> So, the C++ version seems not to segfault, but the issue is that it uses different API for JITting (which is old and deprecated right not, btw). I'm currently struggling to map it to the new API through inkwell <-> llvm-sys <-> llvm-c <-> llvm-c++ chain. It seems I'll need more time to investigate this.

**Comment by OlegTheCat** [comment]
Regarding the C version of Kaleidoscope, I didn't know it exists, to be honest. Can you point me where to look?  As far as I can see there are [two official implementations of Kaleidoscope: in C++ and in OCaml](https://llvm.org/docs/tutorial/index.html).

**Comment by TheDan64** [comment]
Sorry, it seems you're right that there isn't an official C Kaleidoscope - however I was thinking there's gotta be some out there that might be worth checking out? In which case we could get a close comparison to inkwell since we're also using the C api.

Maybe this one? https://github.com/benbjohnson/llvm-c-kaleidoscope

**Comment by TheDan64** [comment]
Also, I'm guessing the OCaml uses the C api behind the scenes?

**Comment by OlegTheCat** [comment]
Yeah, right. I'll check the OCaml version then.

**Comment by TheDan64** [comment]
Fixed by #76

**Comment by tolziplohu** [comment]
This seems to be a problem again, at least on LLVM 10.0.0. When I try
```
?> extern printd(x)

?> printd(10)
```
in Kaleidoscope, it segfaults. `nm` doesn't see the `printd` symbol, but even when I add `#[inline(never)]` and call it from `main()`, so `nm` sees it again, it still segfaults.
